### ISSUE TITLE
Provide View Helper?

### ISSUE THREAD

**Issue by intellent** [zendframework/zend-escaper#14]
Afaik ZF2 doesn’t ship a default View Helper to escape strings within view scripts. The [docs](http://framework.zend.com/manual/current/en/modules/zend.escaper.escaping-html.html) say you need to instantiate a custom escaper in the view script.

This seems clunky to me. Is there any reason, zend-escaper doesn’t provide a View Helper?

**Comment by intellent** [comment]
Sorry. Just found out there’s a View helper. You may call `$this->escapeHtml($myString)` in view scripts. Didn’t see this in the docs though.

**Comment by froschdesign** [comment]
@intellent 

> Didn’t see this in the docs though.

Can you create a ticket for this in the [issue tracker of `Zend\View`](https://github.com/zendframework/zend-view/issues)? Thanks!
